### ISSUE TITLE
@auto_close_db usage question

### ISSUE THREAD

**Issue by paulochf** [smartfile/django-mysqlpool#10]
The Readme says:

> Once we decorated all functions that utilized a connection, this service used less connections than it's total thread count.

In my case, I have a Django command where I want to use the decorator. This command imports some functions and classes from the project. So, for example, in a 5-level execution flow would be something like (tree levels are ok, markdown messed a little):

* Django command
 * view1/function1
   * view1/function2
     * view2/function1
       * view3/function1, which has SomeModel.objects.___ call

Do I have to decorate the command all the execution tree down to the bottom function where Django uses a connection, or decorating just the main function (in my example, the Django command one) is enough?

Thanks!

**Comment by travcunn** [comment]
The decorator simply runs the function it is decorating and then closes all connections.

You could just decorate the main function and it should work ok.

**Comment by paulochf** [comment]
Thanks!

I'm going to test it this night. I'm having trouble with Django and long-time Django command runnings, getting "MySQL server has gone away" error.

I hope this will work.

**Comment by travcunn** [comment]
If you are having trouble with long running Django commands, it may be more beneficial to use the decorator where the database is being accessed. This way, database connections will close after each function runs.

If you use the decorator on the main function, the decorator will only run once.

**Comment by paulochf** [comment]
Fair enough. I'll write about it between friday and monday.

**Comment by paulochf** [comment]
Fair enough. I'll write about it between friday and monday.

Meanwhile, I don't want to miss any detail: if my function is `@transaction.atomic`, I have to do

    @auto_close_db
    @transaction.atomic
    def fun():
        ...

right?

**Comment by paulochf** [comment]
FYI, it seems it's working.

I was used to have problems every day, because the application had long idle periods of time, causing open connection timeouts (at least, it's the explanation given by [Django guys in their thread](https://code.djangoproject.com/ticket/21597).

Since Thursday-Friday night, when I deployed this code, it's up since there.

Thanks by the help, for anything else I'll come back.
